version: "3"
services:
  # /etc/hosts add 127.0.0.1	prometheus
  prometheus:
    image: prom/prometheus:v2.16.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus-dev.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=200h'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - monitor-net

  # URL: http://prometheus:9090
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - $DOCKER_VOLUMES/grafana/datasources:/etc/grafana/datasources
      - $DOCKER_VOLUMES/grafana/dashboards:/etc/grafana/dashboards
      - $DOCKER_VOLUMES/grafana/setup.sh:/setup.sh
      - $DOCKER_VOLUMES/grafana/data:/mnt/data
      - $DOCKER_VOLUMES/grafana/logs:/mnt/logs
      - $DOCKER_VOLUMES/grafana/var/lib/grafana:/var/lib/grafana
    networks:
      - monitor-net

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - boilerplate-net

  boilerplate:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: boilerplate
    ports:
      - "8080:8080"
    networks:
      - boilerplate-net

networks:
  boilerplate-net:
    driver: bridge
  monitor-net:
    driver: bridge
